### ISSUE TITLE
`make lint` failing on master HEAD

### ISSUE THREAD

**Issue by maqiuyujoyce** [GoogleCloudPlatform/k8s-config-connector#1488]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

Here is the error log when running `make lint` against master HEAD:

```
level=error msg="Running error: can't run linter goanalysis_metalinter\nfindcall: failed to load package mockmonitoring: could not load export data: no export data for \"github.com/GoogleCloudPlatform/k8s-config-connector/mockgcp/mockmonitoring\""
```

It's interesting to see the lint issue at HEAD because all the PRs are supposed to pass the lint test.

**Comment by acpana** [comment]
Thanks for opening this Joyce! I'm fairly certain Justin fixed any lint failures on `HEAD` with https://github.com/GoogleCloudPlatform/k8s-config-connector/pull/1491. I think the issue was a bad bot merge 🤔 I'll have a look in my downtime at https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/1239 which probably would prevent things like this
