### ISSUE TITLE
Support GCP Cloud Firestore and Cloud Firestore Indexes 

### ISSUE THREAD

**Issue by AlexBulankou** [GoogleCloudPlatform/k8s-config-connector#18]
Requested in multiple customer conversations, so opening GH issue to allow subscribing for updates to get notified when support is implemented

**Comment by jcanseco** [comment]
Updating this thread to say that Config Connector has had support for the creation of Cloud Firestore Indexes for quite some time now via the `FirestoreIndex` resource. See the resource's documentation [here](https://cloud.google.com/config-connector/docs/reference/resources#firestoreindex).

**Comment by numbsafari** [comment]
This is kind of confusing. You can create an Index but you can't actually create a collection that is the target/subject of the index.

Bizarre.

**Comment by jcanseco** [comment]
Hi @numbsafari, agreed that it is quite strange. The reason is that the [Firestore API](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases.collectionGroups.indexes) at the time did not support the ability to provision anything other than indexes. Even now, I believe it is still not possible to provision collections via the API. You'll see that Terraform also supports only [indexes](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_index) and (just recently) [documents](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/firestore_document).

If you need support for other Firestore resources (whether they're supported by the API or not), then please feel free to open an issue and we'll look into what we can do.

**Comment by PatrickChenSe** [comment]
@jcanseco are there any changes on this? We are looking for support for the cloud firestore from KCC.

**Comment by jcanseco** [comment]
Hi @PatrickChenSe no we do not have an update unfortunately; I recommend using something else to manage Cloud Firestore in the meantime since I do not think we will be getting to expanding our Firestore support any time soon.

**Comment by tylertreat** [comment]
I think this needs reopened. Firestore/Datastore now supports multiple databases in a project and creating new databases [from the REST API](https://cloud.google.com/firestore/docs/reference/rest/v1/projects.databases/create) and gcloud CLI.

https://cloud.google.com/blog/products/databases/manage-multiple-firestore-databases-in-a-project

https://cloud.google.com/firestore/docs/manage-databases
