### ISSUE TITLE
Documentation: Add-on installation mode unnecessary mentions GSA

### ISSUE THREAD

**Issue by redbaron** [GoogleCloudPlatform/k8s-config-connector#190]
[Instructions](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#add-on) for configuring add-on installation contain step **Configuring Config Connector**  with following:

```
  # the default Google Service Account used by ConfigConnector to authenticate Google Cloud APIs
  googleServiceAccount: "[GSA]@[PROJECT_ID].iam.gserviceaccount.com"
```

This service account is never actually created and not mentioned in installation instructions for a second time. I wonder if it is a leftover from some copy paste.

**Comment by maqiuyujoyce** [comment]
Hi @redbaron, thank you for your feedback! We will look into how we can improve the installation instructions. Will keep you updated.

**Comment by TravRan** [comment]
I'm also struggling with the KCC-Add on configuration. I opened up Case 23697755 for the issue. What permissions does the default Google Service Account used by ConfigConnector need for the  host project?

**Comment by caieo** [comment]
Hi @TravRan,
The default Google Service Account used by ConfigConnector needs `roles/owner` as a minimum. Depending on what APIs you're using and what permissions are required to interact with that API, you may need to add permissions when needed. For your case, it looks like you're trying to use ConfigConnector to create a service account, and the service account API requires [these permissions](https://cloud.google.com/iam/docs/creating-managing-service-accounts#permissions) in order to be able to create a service account. You'll need to ensure ConfigConnector has the permissions for this. I believe I'm working with the support engineer on addressing your issue, so we can continue troubleshooting there.

**Comment by caieo** [comment]
Hi @TravRan,
The default Google Service Account used by ConfigConnector needs roles/owner as a minimum. Depending on what APIs you're using and what permissions are required to interact with that API, you may need to add permissions when needed. I'm working with the support engineer on your particular case, but it might not be related to permissions.

**Comment by xiaobaitusi** [comment]
Hi @TravRan,
The default GSA is now deprecated in favor of the GSA specified in the `ConfigConnectorContext`. That instruction step has been corrected now. Thanks for reporting this issue. 

Since there is no default GSA, the GSA specified in the `ConfigConnectorContext` should have the appropriate roles for the managed project. We recommend to grant roles/editor access to the managed project to allow most Config Connector functionality except Project or Organization wide configurations such as Cloud IAM modifications. But it really depends on what GCP services you plan to use.

**Comment by redbaron** [comment]
I can see updated docs removed mention of unused GSA, closing now. Thanks for a quick turnaround!
