### ISSUE TITLE
GCP authorization of Config Connector in multi-tenant clusters

### ISSUE THREAD

**Issue by yhrn** [GoogleCloudPlatform/k8s-config-connector#26]
To use Config Connector in production we would need it to be installed in a multi-tenant cluster and then we need a way of authorizing Config Connector's GCP SA to create resources in our GCP project but only in specific k8s namespaces. 

One suggestion here is to be able to use a member syntax similar to the one used for Workload Identities. For example, say Config Connector uses the GCP SA `cnrm-system@shared-gke-proj.iam.gserviceaccount.com` and I have mapped the k8s namespace `ns1` to the GCP project `gcp_proj_1`, then I would add a project IAM policy binding making  `cnrm-system@shared-gke-proj.iam.gserviceaccount.com[ns1]` owner in `gcp_proj_1`.

**Comment by kibbles-n-bytes** [comment]
We are brainstorming having a mode where Config Connector operates as a namespace-scoped operator. This would require having a pod per namespace where GCP resources will be actuated, but it would dramatically scope both the RBAC and IAM permissions. And that pod could then make use of workload identity so that no key management would be required. Would this fulfill your use case?

The CRDs and validating webhooks would still need to be deployed by the cluster admin.

**Comment by yhrn** [comment]
I'd say that would fulfill our use case. I guess this could make it a bit more cumbersome to manage the Config Connector controller but an upside could be that it might scale better and avoid interference between different namespaces/projects.

**Comment by kibbles-n-bytes** [comment]
Closing out this issue  as, as of our 1.0.0 release, Config Connector now includes namespaced-mode support. Please see the last tab in https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall , and https://cloud.google.com/config-connector/docs/concepts/installation-types for more information.

The installation itself is notably a bit complex. We are actively working on ways to make the installation, upgrade, and management of Config Connector installations easier.
