### ISSUE TITLE
SQLInstance fails to update with self-link for privateNetworkRef

### ISSUE THREAD

**Issue by Magic-Mayo** [GoogleCloudPlatform/k8s-config-connector#2701]
### Checklist

- [X] I did not find a related open issue.
- [X] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [X] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Bug Description

When upgrading to version 1.122.0 we found that the `settings.ipConfiguration.privateNetworkRef.external` field for a SQLInstance seems to have changed.  According to the message, the format is required to be `projects/<project id>/global/networks/<networkid>`.  Previously, it was just a self-link to the network to be used.  We do not and have not used a global network for our VPC and I'm not sure why that's required now.  The issue seems to be [here](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/pkg/controller/direct/sql/normalize.go#L245) which leads [here](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/apis/refs/v1beta1/computerefs.go#L53-L65).

There doesn't seem to be any mention of this in the release notes either.  Please advise on what to do if this is not a bug.

### Additional Diagnostic Information

This happened on all our clusters running different versions of k8s.  Rolling back to version 1.121.0 brought everything back.

### Kubernetes Cluster Version

v1.29.7-gke.1274000

### Config Connector Version

1.122.0

### Config Connector Mode

namespaced mode (default)

### Steps to reproduce the issue

1. Install ConfigConnector v1.121.0
1. Create a SQLInstance with an external privateNetworkRef to a shared VPC
1. Upgrade ConfigConnector to v1.122.0
1. Wait until after next reconcialiation, or alternatively apply an annotation/label to force a reconciliation, then see error on SQLInstance object

**Comment by yuwenma** [comment]
Thanks for reporting the issue @Magic-Mayo. We are trying to normalize the resource reference "External" value to make it more self-explained,  directly associated with the Config Connector resource GCP identifier and eliminate confusions like "ProjectID" vs "ProjectNum" cases. 

Previously, Config Connector does not have enough information about what the actual GCP "External" value is, and cannot always identity and acquire the resource accurately. Now we are making this better by migrating the resource from TF-based to a more Kubernetes native direct approach. This progress may introduce some gaps for users because we want to give a more clear recommendation about how the External field should be used. Ideally, we would expect users to update their config according to the error message. For Beta resources, we will continue supporting the old behavior (like `SelfLink`, but we cannot discover all cases until we see the issue reports). 

In the next releases, we will add a backward compatibility patch for all ComputeNetwork references (and some other Compute resources), and you can continue using the `SQLInstance` the way you use it today. Again, thanks for reporting the issue.

**Comment by Magic-Mayo** [comment]
Thank you for confirming the issue.  Most of my concern here is it's undocumented and while I understand the reasoning for moving to a more unified format, it wasn't understood at the time of upgrading and we had to dig around to figure out what was going on.

**Comment by yuwenma** [comment]
Thank you so much for the feedback! Maybe we should give more information about what the potential risk could be when putting the `SQLInstance` under the "Direct Cloud Reconciler" (that is how we announce a resource is migrated to the direct approach right now)? Do you think that could help?

**Comment by Magic-Mayo** [comment]
I haven't seen much about direct reconciliation.  I've tried to find more information on it but really all I could find was a short description in the release notes.  It doesn't need much more explanation on what's happening as it's clear from the notes that specific resources are no longer provisioned via terraform but it would be nice to have some kind of documentation you could point me to so I can learn more about it.

To answer the question, I think some kind of warning, if needed, in the release notes when a resource moves to direct reconciliation would be very helpful.  I would almost want to say this should be considered a breaking change as ConfigConnector can no longer reconcile this specific resource, `SQLInstance`, when the `privateNetworkRef` is not in the new format.

**Comment by Magic-Mayo** [comment]
Thank you for the explanation @justinsb , that was very helpful!

**Comment by jasonvigil** [comment]
@Magic-Mayo can you please give an example of a `settings.ipConfiguration.privateNetworkRef.external` value you are using? I am not sure our new direct controller actually supports shared VPC yet. Are you specifying a self link to the subnetwork (not network) in the host project?

**Comment by Magic-Mayo** [comment]
We are using a self link to the VPC network, not a subnetwork.  It ends up looking like

```
https://www.googleapis.com/compute/v1/projects/<project id>/global/networks/<network id>
```

Based on some of the code I was looking at I would think this is supported already.  When I initially made the issue, we were frantically trying to rectify the problem and I misspoke about what the format of the link to the shared VPC is.  It in fact does include a reference to a global network in the path so it seems as though a shared VPC network would fit the required format for the direct controller.

But, I don't develop or maintain the project at all so I will let the experts figure it out 😅

**Comment by jasonvigil** [comment]
@Magic-Mayo that's great, thank you for confirming!
