### ISSUE TITLE
cnrm-controller-manager crashes on unused artifactregistryrepositories resource

### ISSUE THREAD

**Issue by Scorpiion** [GoogleCloudPlatform/k8s-config-connector#287]
**Describe the bug**
I get this error in my logs (`kubectl logs -f -n cnrm-system cnrm-controller-manager-XXXXXXXXXXX-0 manager`) and it seems like it stops config connector for working completely. Sometimes it shows `starting reconcile` for some resources but most resources are never reconciled.

```
E1005 17:39:08.639075       1 reflector.go:178] sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:224: Failed to list artifactregistry.cnrm.cloud.google.com/v1beta1, Kind=ArtifactRegistryRepository: artifactregistryrepositories.artifactregistry.cnrm.cloud.google.com is forbidden: User "system:serviceaccount:cnrm-system:cnrm-controller-manager-XXXXXX" cannot list resource "artifactregistryrepositories" in API group "artifactregistry.cnrm.cloud.google.com" in the namespace "XXXXXX"
```

The odd thing in this is also that I don't use artifactregistry at all.

**ConfigConnector Version**
``` 
# GKE version
1.17.9-gke.1504

# Config Connector addon
1.15.1
```

**To Reproduce**
Honestly I'm not sure how to reproduce this since I'm not sure what causes it. I'm using the GKE addon and config connector in different namespaces. I have checked that workload identity works with the test container, this works as it should:

```
kubectl run -it --image google/cloud-sdk:slim --serviceaccount cnrm-controller-manager-XXXXXX --namespace cnrm-system workload-identity-test

gcloud auth list
```

I know that 1.15.1 is a bit old based on (https://github.com/GoogleCloudPlatform/k8s-config-connector/releases), but as I understand it with the addon I can not updated it manually and it should be updated via GKE. I have the latest GKE version according to the GKE UI (for the release channel "Regular"). Is it correct that the Regular channel should be so behind on the addon version or is something wrong with the addon update process?

Not sure if it's relevant, but maybe, in the release notes it says for release 1.16: 
> Adds support for ArtifactRegistryRepository
> https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.16.0

And as mentioned above, I'm on 1.15.1 according to this command:
```
kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'
```

It's worth noting that I have upgraded from a manual install of config connector to using the GKE addon. I did to my knowledge fully delete everything of the old installation before installing the addon though (based on the docs), so it should not affect things, but I'm mentioning it just in case.

**Comment by jcanseco** [comment]
Hi @Scorpiion. It looks like there was likely an installation of KCC 1.16+ that wasn't fully cleaned up (which includes a new CRD, `ArtifactRegistryRepository`), and so when you installed the KCC GKE Add-on (which is on an older KCC version, 1.15.1), the KCC controller started error-ing out since it did not have permissions to list the new CRD.

The error message you're seeing looks like the one observed [here](https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/242#issuecomment-659068744) where another user performed an in-place downgrade of KCC (not recommended).

As a sanity check, can you please check that the controller itself has the right version (1.15.1):
```
kubectl -n cnrm-system get pod cnrm-controller-manager-XXXXXXXXXXX-0 -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'
```

And that the `ArtifactRegistryRepository` CRD does exist:
```
kubectl get crd artifactregistryrepositories.artifactregistry.cnrm.cloud.google.com
```

Once you confirm that your controller is on v1.15.1 and that the `ArtifactRegistryRepository` CRD exists, you have two options:
1. Wait for GKE to auto-upgrade KCC.
1. Delete the `ArtifactRegistryRepository` CRD yourself. We would not normally recommend this, but if you need to unblock yourself ASAP and you do not have any `ArtifactRegistryRepository` resources currently, then it should be safe to do so in this case.

**Comment by Scorpiion** [comment]
Hi @jcanseco and thanks for the fast feedback!

I check the controller version and got this (same version)
```
1.15.1
```

And yes the CRD does exists:
```
kubectl get crd artifactregistryrepositories.artifactregistry.cnrm.cloud.google.com
NAME                                                                  CREATED AT
artifactregistryrepositories.artifactregistry.cnrm.cloud.google.com   2020-09-22T23:39:25Z
```

I removed the CRD, at first it seems like I keep getting the same error message. However, after I deleted the pod and it has been recreated, then it started working. :+1:

**Comment by jcanseco** [comment]
No problem! And thanks for providing the level of detail that you did in your initial bug report :)
