### ISSUE TITLE
Will GCP resources be kept when uninstalling configconnector?

### ISSUE THREAD

**Issue by Bobgy** [GoogleCloudPlatform/k8s-config-connector#306]
Describe your question when using ConfigConnector, feel free to check our official documents for more context. 
* [Product Overview](https://cloud.google.com/config-connector/docs/overview)
* [Resource Reference](https://cloud.google.com/config-connector/docs/reference/resources)

When I delete `configconnector` instance, I found that managed GCP resources are still kept, even though the cnrm resources have been deleted in the cluster (because CRDs are deleted).

I want to confirm whether this is the desired behavior, will it keep this way?

(For me, this sounds like a reasonable and convenient way to use config connector to install some resources and then uninstall it. The next time when I need to update those resources, I can install again and apply resources built from my manifest)

**Comment by jcanseco** [comment]
Hi @Bobgy, yes you're correct that GCP resources are not deleted when uninstalling KCC. This was an intentional design decision: we wanted to avoid the scenario of users unintentionally mass-deleting their GCP resources by uninstalling KCC (and thereby causing an outage). This is consistent with KCC's product philosophy of deleting resources if and only if the user explicitly tells it to (e.g. via `kubectl delete`).

If you do want to mass-delete your resources, you could so do using:

```
kubectl delete gcp --all --all-namespaces
```

Thanks for the question. Closing now; though please feel free to re-open if you have any follow-up questions.

**Comment by Bobgy** [comment]
Thank you for the quick reply!

I was a little confused because I didn't find related documentation on GCP until I actually try it.

Totally makes to me!
