### ISSUE TITLE
How long will old way of manual installation be supported?

### ISSUE THREAD

**Issue by tonybenchsci** [GoogleCloudPlatform/k8s-config-connector#355]
We noticed on https://cloud.google.com/config-connector/docs/how-to/advanced-install#manual, that the manual instructions have changed from using gs://cnrm/ to gs://configconnector-operator/

We've been installing KCC on GKE since version 1.0.0 using the manual workload identity approach, for more direct control and upgrades.

Will the old (now not documented) way still be supported in the foreseeable future? I do see the latest bundel 1.33.0 also inside of gs://cnrm/

Our upgrade script:

```
# Uninstall current version (state of GCP resources will be preserved)
kubectl delete sts,deploy,po,svc,roles,clusterroles,clusterrolebindings --all-namespaces -l cnrm.cloud.google.com/system=true --wait=true
kubectl delete validatingwebhookconfiguration abandon-on-uninstall.cnrm.cloud.google.com --ignore-not-found --wait=true
kubectl delete validatingwebhookconfiguration validating-webhook.cnrm.cloud.google.com --ignore-not-found --wait=true
kubectl delete mutatingwebhookconfiguration mutating-webhook.cnrm.cloud.google.com --ignore-not-found --wait=true

# Download desired version
gsutil cp gs://cnrm/$VERSION_DESIRED/release-bundle.tar.gz release-bundle.tar.gz
tar zxvf release-bundle.tar.gz
rm -rf samples/ release-bundle.tar.gz install-bundle-gcp-identity/ install-bundle-namespaced/
sed -i .bak 's/${PROJECT_ID?}/OUR_PROJECT/' install-bundle-workload-identity/0-cnrm-system.yaml

# Install desired version
kubectl apply -f install-bundle-workload-identity/
```

**Comment by spew** [comment]
Hello Tony,

The operator approach is the only supported mode going forward. What you are doing will continue to work for the time being but there is no guarantee.

**Comment by tonybenchsci** [comment]
Thanks for getting back @spew . I image there are many customers who started using (installing/upgrading) before the Operator installation (and docs) were introduced, so obviously we're hoping for continued support with the old appraoch.

Has there been problems switching install mode from manual workload-identity to manual operator approach?
We'd need to change our install script and documentation.  

The concerns would be whether uninstalling KCC (old way), and re-installing it (new way) would be seemless and acquire all our resources across multiple projects. Would you also recommend doing it on a fresh cluster, and would that new cluster have any problems acquire existing GCP resources?

**Comment by spew** [comment]
Hi @tonybenchsci we have not heard of problems switching. I would recommend testing the change to the new mechanism on a on a new/test cluster (with new resources). After you are sure it works, then I would run it on your production cluster.

**Comment by toumorokoshi** [comment]
We've added [some upgrade instructions](https://cloud.google.com/config-connector/docs/how-to/advanced-install#upgrading_from_non-operator_installations) in the help documentation. 

To add to @spew's comment, acquiring existing resources work for most resources, but it can cause issues with resources that do not uniquely identify with the display name of the resource (e.g. folders). For that reason, I would not recommend building a new cluster and re-acquiring existing resources, and instead do an in-place upgrade. 

The instructions added above describe who to do so.

**Comment by toumorokoshi** [comment]
I'll close this issue for now, since we provided some documentation and answered the question. feel free to re-open if you have further questions. 

Also taking a quick look at your upgrade script, it will almost work if you just switch the operator bundle, but you will need to add a [ConfigConnector custom resource](https://cloud.google.com/config-connector/docs/how-to/install-upgrade-uninstall#addon-configuring) if you haven't already: the operator reads that configuration before deploying the new controllers.

**Comment by tonybenchsci** [comment]
Thanks @toumorokoshi , but I guess to upgrade from non-operator installations, we would have to ignore "Create or identify a GKE cluster where Config Connector has not yet been installed..." part from https://cloud.google.com/config-connector/docs/how-to/advanced-install#before_you_begin ?

**Comment by jcanseco** [comment]
Hi @tonybenchsci, I had no idea GitHub doesn't actually let non-collaborators re-open issues. Thanks for letting us know :)

> I guess to upgrade from non-operator installations, we would have to ignore "Create or identify a GKE cluster where Config Connector has not yet been installed..." part from https://cloud.google.com/config-connector/docs/how-to/advanced-install#before_you_begin since we're not doing a fresh install?

That is correct.

> Also I guess your suggestion to not re-acquire from a new cluster [...] doesn't preclude @spew 's suggestion to first do a full install on a new cluster just to be familiar (write a script) before messing with our actual production cluster?

That is correct.

>  (btw, what other resources behave like 'folders' where it might have trouble?)

**Short answer**: resources with server-generated IDs:
* `AccessContextManagerAccessPolicy`
* `CloudBuildTrigger`
* `DataflowFlexTemplateJob`
* `FirestoreIndex`
* `Folder`
* `IAMServiceAccountKey`
* `MonitoringAlertPolicy`
* `MonitoringNotificationChannel`
* `ResourceManagerLien`
* `SQLSSLCert`
* `SecretManagerSecretVersion`
* `StorageNotification`
* `StorageTransferJob`

**Long answer**: resources can generally be classified into two categories: 
1. Those with **user-specified IDs**: the identifier of the resource is configured by the user (e.g. the name of a `SpannerInstance`).
2. Those with **server-generated IDs**: the identifier of the resource is generated by the server after the resource is created (e.g. the ID of a `StorageNotification`).

~10% of KCC resources fall into the latter category. For some time, there had been no way to acquire such resources since you couldn't specify server-generated IDs in the config; such fields only appeared in the status.

We're in the process of rolling out support for the `spec.resourceID` field for our resources, which _would_ allow you to specify the server-generated ID of a resource and thus acquire it.

Both user-specified ID and server-generated ID resources will be made to support `spec.resourceID` (e.g. so that you can specify the name of a `BigQueryDataset` using `spec.resourceID` instead of `metadata.name`, thus avoiding K8s naming restrictions).

However, for server-generated ID resources, `spec.resourceID` can only be used for acquisition as opposed to in user-specified IDs where you can use `spec.resourceID` for both creation and acquisition. We plan to document this in the `description` of `spec.resourceID`, and this is how you'll be able to tell if a resource is a server-generated ID resource (i.e. by seeing that its ` spec.resourceID` can only be used for acquisition).

This is because it is not possible to write a config that you can use for _both_ resource creation and acquisition in the server-generated ID case, since you necessarily do not know the server-generated ID before actually creating the resource.

> 3rd question I have is if there'll be issues using the same GCP IAM service account from two different cluster workload identities?

No, there should be no issues there.

**Comment by tonybenchsci** [comment]
Thanks @jcanseco . I'm closing this as we've successfully re-installed v1.33.0 using Operator using your docs.
