### ISSUE TITLE
KCC Host Project Cloud Resource Manager API Read Requests

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#364]
**Describe the bug**
We've noticed that our KCC Host Project keeps running up against the Cloud Resource Manager Read Request Quota. We requested the quota be bumped to 2000 to see if that resolved our issue. It appears that isn't enough. Couple questions, first, do you have any idea what the ratio should be per project? Second, is there a way to reduce the number of scans KCC is doing to the managed projects?

![image](https://user-images.githubusercontent.com/75803296/104331493-be63f380-54b4-11eb-805a-c022386217eb.png)

**ConfigConnector Version**
Run the following command to get the current ConfigConnector version
v1.33.0

**Comment by caieo** [comment]
Hi @travisrandolph-bestbuy, thanks for bringing this to our attention. To help get more context on why this is happening can you share if you are using ConfigConnector in the namespaced mode? Can you also specify roughly how many projects/namespaces your host project is managing? It'd also be helpful to know what resources you're mainly using. 

To answer your questions:
> do you have any idea what the ratio should be per project? 

We haven't encountered this issue before, so I can't give you a good idea of what the ratio should be.

> is there a way to reduce the number of scans KCC is doing to the managed projects?

Unfortunately, there's not much that can be done unless we modify what is causing those read requests. If you're using namespaced mode, can you check if the service accounts are being created in the host project or in the separate projects?

**Comment by travisrandolph-bestbuy** [comment]
@caieo Yes we are using namespaced mode. We are currently managing 31 projects in the cluster. The SA used to manage each project is created in the host project.

**Comment by caieo** [comment]
@travisrandolph-bestbuy I think we know the issue. Because you're using the same host project's SA for each new namespace, each project's request to GCP will be compounded onto to the host project's quota (quota is attached to the GSA's project by default). 

We actually implemented a feature in our ConfigConnectorContext that should solve this issue, but unfortunately have not published documentation for it yet. In release [1.28.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/1.28.0), we added a field `spec.requestProjectPolicy` which you can set to `RESOURCE_PROJECT`. This will indicate to the operator to use the created project's quota instead of the host project's quota. You can read the description for the field in the ConfigConnectorContext's CRD, but I will paste it here too: 
```
requestProjectPolicy:
  description: Specifies which project to use for preconditions, quota,
   and billing for requests made to Google Cloud APIs for resources in
   the associated namespace. Must be one of 'SERVICE_ACCOUNT_PROJECT'
   or 'RESOURCE_PROJECT'. Defaults to 'SERVICE_ACCOUNT_PROJECT'. If set
   to 'SERVICE_ACCOUNT_PROJECT', uses the project that the Google Service
   Account belongs to. If set to 'RESOURCE_PROJECT', uses the project
   that the resource belongs to.
```

**Comment by travisrandolph-bestbuy** [comment]
Thanks @caieo. We'll do some testing on our end and get back.

**Comment by travisrandolph-bestbuy** [comment]
@caieo The feature is working as expected. 

![image](https://user-images.githubusercontent.com/75803296/105092037-5722e200-5a66-11eb-85f8-4bdb2b1a908d.png)

**Comment by travisrandolph-bestbuy** [comment]
@caieo Randomly today we started having an issue with new projects and enabling their API's. More specifically it looks to be the Resource Manager API. After some troubleshooting we decided to remove the "requestProjectPolicy: RESOURCE_PROJECT" field from the project's ConfigConnectorContext and then KCC was able to enable the Resource Manager API on the managed project again. Any idea as to what is happening? Below is the error snippet that we receive until we remove the "requestProjectPolicy: RESOURCE_PROJECT" from the ConfigConnectoContext. FYI, this affected both our Dev and Prod clusters.

`
 Warning  UpdateFailed  104s (x45 over 10h)  service-controller  Update call failed: error fetching live state: error reading underlying resource: summary: Error when reading or editing Project Service projects/{{REDACTED}}/services/: googleapi: Error 403: Cloud Resource Manager API has not been used in project {{REDACTED}} before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/cloudresourcemanager.googleapis.com/overview?project={{REDACTED}}then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry., accessNotConfigured, detail
`

**Comment by maqiuyujoyce** [comment]
Hi @travisrandolph-bestbuy , thanks for the follow up. When you set `requestProjectPolicy: RESOURCE_PROJECT`, you are using the allowed preconditions in your managed project to create all resources including `Service` resources. One precondition is for the API enablement. Config Connector [uses the Resource Manager API to enable service APIs](https://cloud.google.com/config-connector/docs/how-to/getting-started#before_you_begin). If Resource Manager API is not enabled in your managed project already, then Config Connector cannot enable any other APIs. That's why the error message said `Error 403: Cloud Resource Manager API has not been used in project {{REDACTED}} before or it is disabled.`

If you have had the Cloud Resource Manager API enabled after removing `requestProjectPolicy: RESOURCE_PROJECT`, feel free to add the config back if you still want to use the managed project to reduce the quota load on the host project. The resource in your namespace should be working fine.

For any similar situation in the future, I suggest that you can have a different namespace that manages all the configurations of the managed projects, or you can enable the Cloud Resource Manager API at the time you create the managed project via Config Connector.

**Comment by travisrandolph-bestbuy** [comment]
@maqiuyujoyce One of our best ways to work around this would be to use the GSA/namespace that creates the projects. The problem is gcp services. Right now you can only enable one specific service per namespace as the name of the resource has to be the name of the api. I think there may be an issue for that enhancement though.

**Comment by maqiuyujoyce** [comment]
Hi @travisrandolph-bestbuy , you seem to be using Config Connector v1.33.0, and since that version, we support resourceID overrides for the `Service` resource. You should be able to manage multiple `Service` resources of the same API for different projects in the same namespace like below. More information about the resourceID field can be found in the [public documentation](https://cloud.google.com/config-connector/docs/how-to/managing-resources-with-resource-ids).

```
apiVersion: serviceusage.cnrm.cloud.google.com/v1beta1
kind: Service
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: [PROJECT_ID]
  name: compute-service
spec:
  resourceID: compute.googleapis.com
```

**Comment by travisrandolph-bestbuy** [comment]
@maqiuyujoyce We'll give the resourceID a go and report back.

**Comment by travisrandolph-bestbuy** [comment]
@maqiuyujoyce resourceID works as intended. Thank you for your help. Closing the issue.
