### ISSUE TITLE
Add external reference to DNSRecordSet for ComputeAddress

### ISSUE THREAD

**Issue by raffomartini** [GoogleCloudPlatform/k8s-config-connector#457]
**Describe the feature or resource**

Add an external reference to ComputeAddress.address for elements of DNSRecordSet.rrdatas as alternative option to string

**Importance**

**Comment by aw185176** [comment]
Would be huge for us as well

**Comment by caieo** [comment]
Hi @aw185176 and @raffomartini, thank you for the added interest in this feature. There is currently an open issue thread for this (https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/101) that we have posted updates on. The general takeaway is that we're aware that this will be a huge improvement in many of our user's experience, and want to couple this backwards-incompatible change with work to support multiple versions. Unfortunately, we haven't found the time to address infrastructure improvements like this would entail and don't have a clear timeline on when this will be supported by. 

Because this is a duplicate issue, I will close it. Please chime in on the original issue (https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/101) and monitor it for future updates!
