### ISSUE TITLE
ResourceRef type appears to be wrong for IAMPolicyMember Go client

### ISSUE THREAD

**Issue by aw185176** [GoogleCloudPlatform/k8s-config-connector#458]
## Checklist

- [x] I did not find a related open issue.
- [x] I did not find a solution in the troubleshooting guide: (https://cloud.google.com/config-connector/docs/troubleshooting)
- [ ] If this issue is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

## Bug Description
IAMPolicyMember uses v1alpha1.ResourceRef: https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/fdae6c138646894b774d6247633abc23dc63846e/pkg/apis/iam/v1beta1/iampolicymember_types.go#L74

v1alpha1.ResourceRef does not support Kind and APIVersion, which are required fields on IAMPolicyMember objects for referencing other KCC resources, per the examples and my own personal experience writing these types before they were released publicly.

**Comment by caieo** [comment]
Hi @aw185176, thanks for trying our go-client out and sorry for this inconsistency. We are aware of this issue already (https://github.com/GoogleCloudPlatform/k8s-config-connector/issues/413) and are currently working on a fix for it. We should have it fixed within the next few weeks and will make sure to update that original thread when it is fixed. (going to close this thread in the meantime because it is a duplicate)

**Comment by aw185176** [comment]
Thanks, I did a quick check and missed that issue before I opened this.
