### ISSUE TITLE
CLI bulk-export error 400 asia-south2 unknown region

### ISSUE THREAD

**Issue by rdoursenaud** [GoogleCloudPlatform/k8s-config-connector#460]
Trying to export an organization or a project using `bulk-export`, config-connector stops on a `ComputeSubnetwork` because the region field is `asia-south2`.

This prevents me from performing a resource audit.

Full error message:
```
error in 'config-connector' version '1.49.0': error getting next YAML: error getting unstructured: error getting next unstruct: error getting '//compute.googleapis.com/projects/[redacted]/regions/asia-south2/subnetworks/default': error fetching live state: error reading underlying resource: summary: Error when reading or editing ComputeSubnetwork "projects/[redacted]/regions/asia-south2/subnetworks/default": googleapi: Error 400: Invalid value for field 'region': 'asia-south2'. Unknown region., invalid, detail:
```

**Comment by jcanseco** [comment]
Hi @rdoursenaud, is this from a newly created project? And do you observe this same issue if you try to `bulk-export` your other projects as well?

I see that `config-connector` is trying to export the default subnetwork from the `asia-south2` region. However:
1. I don't see `asia-south2` in the [list of supported regions](https://cloud.google.com/compute/docs/regions-zones#available).
2. New projects that I've created don't have a default subnetwork in `asia-south2`.
3. Attempting to create `ComputeSubnetwork` resources in `asia-south2` result in the error `Unknown region`.

It seems that `asia-south2` is a brand new region that is in the process of being turned up ([Delhi](https://cloud.google.com/blog/topics/infrastructure/new-google-cloud-regions-for-2020)). Therefore, the issue we're seeing here is probably due to hiccups with the region's turn up, and we'll just have to wait for those hiccups to be resolved internally.

If you're blocked on this issue, note that it is possible to do some filtering when bulk exporting your resources. See:
1. [How to import your resources from a Cloud Asset Inventory export](https://cloud.google.com/config-connector/docs/how-to/import-export/bulk-export#importing_from_a_local_file), and
2. [How to filter an Asset Inventory export](https://cloud.google.com/config-connector/docs/how-to/import-export/bulk-export#filtering_an_asset_inventory_export_on_stdin).

**Comment by rdoursenaud** [comment]
Hi @jcanseco.

No it’s from an old project I want to migrate to config-connector, hence the export and I get the same result if I try exporting other projects.

`asia-south2` dosn’t appear in the web GUI for me either.

That’s what I inferred from the few information I could get about `asia-south2`.

Now, I didn’t know I could use filtering.
I’ll have a go at that.

Thanks!

**Comment by rdoursenaud** [comment]
Reading the documentation you pointed me towards, I see I’ve also totally missed the `--on-error continue`.
This should be enough to get everything I need.

Sorry for bothering you!

**Comment by jcanseco** [comment]
Great, glad to hear that you've been unblocked @rdoursenaud!
