### ISSUE TITLE
Why are there so many resources requested for "deletiondefender"?

### ISSUE THREAD

**Issue by muffl0n** [GoogleCloudPlatform/k8s-config-connector#469]
Currently, the StatefulSet "cnrm-deletiondefender" requests 1GB RAM and 1/4 CPU per pod.
I see that it was raised/added in the [commit which updated to 1.42.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/commit/f7bb580befdba4cfab55bf7b7cf3a75b97645ce2#diff-d02ebefa57dd9df3d45006dc7c882d3cbd7ff7c8f697ff415de5bb482ac237b2R673). 
Is there any particular reason for this amount of resources? This seems quite excessive and can quickly become a problem in small clusters.

On all of my clusters, the pods use only a fraction of what is requested: Around 64MB RAM and never more than 0.05 CPU.

**Comment by muffl0n** [comment]
Same for "webhook-manager": Requests 128MB RAM, 1/4 CPU per pod. Usage: 20MB RAM and nearly no cpu.

I can understand that RAM and CPU usage may be higher in other scenarios. But looking at one of my clusters (4 nodes e2-medium with each 2GB RAM, 1 CPU), the requests for "Config Connector" are eating up one whole node while CPU usage is lower than 0,1.

**Comment by maqiuyujoyce** [comment]
Hi @muffl0n , thank you for your question! There were some Config Connector users seeing false alarms or running into OOM killed issues (e.g. #240, #282). The issues were caused by the lack of resources for webhook and deletiondefender so we determined to bump up the minimum requirement of CPU and memory for webhook-manager and deletiondefender in version 1.42.0.

**Comment by muffl0n** [comment]
Hey @maqiuyujoyce, thank you very much for your detailed answer and the helpful links!
