### ISSUE TITLE
How to delete a resource that does not allow update which stuck at Deletion state 

### ISSUE THREAD

**Issue by PatrickChenSe** [GoogleCloudPlatform/k8s-config-connector#532]
Hi,

I need to edit a BigQueryDataset in the cluster to add the `cnrm.cloud.google.com/state-into-spec:absent` annotation. 
The only way I can do it is to delete the resource and then re-create it, because the `cnrm.cloud.google.com/state-into-spec:merge` annotation blocks editing the resource. 

```
Name:         completeness-and-accuracy
Namespace:    test
Annotations:  cnrm.cloud.google.com/delete-contents-on-destroy: false
              cnrm.cloud.google.com/deletion-policy: abandon
              cnrm.cloud.google.com/management-conflict-prevention-policy: resource
              cnrm.cloud.google.com/state-into-spec: merge
```
I run `kubectl delete BigQueryDataset completeness-and-accuracy -n test --force=true`, but the resource is still stuck after a few hours. 

The only documentation I can find about [force clean up](https://cloud.google.com/config-connector/docs/troubleshooting#forced-cleanup) only works when resources can be updated. 

Is there a way to bypass this, so I can delete the resource?

**Comment by xiaobaitusi** [comment]
Hi Patrick, can you `kubectl describe` the status of the stuck BigQueryDataset object? Also it might be helpful to query relevant logs using Cloud logging. Here is an example [query](https://cloud.google.com/config-connector/docs/troubleshooting).

Afterward, to unblock yourself, I'd suggest to retry to restart the controller-manager pod for that namespace.  You could identify the pod with the following command. Let us know if that works.
```
kubectl get pod -n cnrm-system  -l cnrm.cloud.google.com/component=cnrm-controller-manager -l cnrm.cloud.google.com/scoped-namespace={RESOURCE_NAMESPACE}
```

**Comment by PatrickChenSe** [comment]
Hi Zeya, the resource status shows
```
Status:
  Conditions:
    Last Transition Time:  2021-08-17T14:13:36Z
    Message:               Update in progress
    Reason:                Updating
    Status:                False
    Type:                  Ready
  Creation Time:           1605605919243
  Etag:                    y03+OZGSE9qmJBGoEoJnhA==
  Last Modified Time:      1629123164916
  Observed Generation:     2
  Self Link:               https://bigquery.googleapis.com/bigquery/v2/projects/xxx
Events:                    <none>
```
And I tried restarting the controller pod and delete again, but it didn't work.

**Comment by xiaobaitusi** [comment]
Hi Patrick, it's unfortunate that restarting the controller pod doesn't work.

How often have you run into this with BigQueryDataset objects?

It seems that the controller got stuck either right before or at the point of applying desired state to underlying resource since the condition says `Update in progress`. 
However what is weird to me is that if it's a deletion workflow, the condition should say `Deletion in progress` rather than `Update in progress`. Can you check if this object has the deletionTimestamp set? Also after you restart the controller pod, what were the full log trace looking like? In theory, I'd expect to see something as follows for this particular resource.
```
starting reconcile
finalizing resource deletion
deletion policy set to abandon; abandoning underlying resource
```

> The only documentation I can find about [force clean up](https://cloud.google.com/config-connector/docs/troubleshooting#forced-cleanup) only works when resources can be updated.

As for force-cleanup by removing finalizers, can you clarify why the resource can not be updated, i.e. removing finalizers?

**Comment by PatrickChenSe** [comment]
Hello, Zeya. The issue has been resolved. It turns out to be a chicken-and-egg situation: we have a gatekeeper constraint to verify the `state-into-spec` annotation, but KCC prevents us from changing it to `absent`. The broken resource was deleted when the constraint was temporarily nuked. So I'm closing it. Thanks
