### ISSUE TITLE
GKE ConfigConnector v1beta1 deprecation in Kubernetes 1.22

### ISSUE THREAD

**Issue by dinvlad** [GoogleCloudPlatform/k8s-config-connector#558]
I've received an email from GCP that `v1beta1` resources will be deprecated soon when GKE clusters are upgraded to Kubernetes `1.22`. We have a lot of custom `ConfigConnector` resources, all of which are currently using `v1beta1`, and it's not documented anywhere when `v1` is supported for these.

Could you clarify if these resources will be affected by the upgrade to `1.22`, and what will be the migration path, if any?

Thank you

**Comment by maqiuyujoyce** [comment]
Hi @dinvlad , thank you for your question. Config Connector has already migrated from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1` for the CRDs since [v1.50.0](https://github.com/GoogleCloudPlatform/k8s-config-connector/releases/tag/v1.50.0) without any changes to the content of the CRDs. So no resource should be affected.

If you plan to upgrade to K8s `1.22`, please ensure your Config Connector version is at or above `v1.50.0`.
