### ISSUE TITLE
CloudIdentityGroup  - Issues acquiring existing Cloud Identity Groups

### ISSUE THREAD

**Issue by tedelwartowski-bestbuy** [GoogleCloudPlatform/k8s-config-connector#584]
One feature we rely on for our automation is resource acquisition via config connector, however it would appear this is not working correctly for **CloudIdentityGroup**. Below is the error we are receiving when trying to deploy a CloudIdentityGroup resource for a group that already exists. Since we already have a large number of Groups in our ecosystem, we were hoping to be able acquire them with out having to re-create. Is resource (group) acquisition even possible via CloudIdentityGroup?

```
"@type": "type.googleapis.com/google.rpc.ResourceInfo",
"description": "Error(2018): Cannot create group 'XXXX@XXXX.com' because it already exists.",
"owner": "domain:cloudidentity.googleapis.com",
"resourceType": "cloudidentity.googleapis.com/Group"
```

**Comment by toumorokoshi** [comment]
Hello! cloud identity groups are given a unique id that we cannot infer. Due to that gap, acquiring existing resources requires the use of a `resourceID` field, populated with the groupID of the cloud identity group. It should look something like:

```
spec:
    ...
    resourceID: "groups/{unique_id}"
```

I'm working on confirming that the format of resourceID for `CloudIdentityGroup` is indeed `groups/{unique_id}` now.

You can [read more about resourceID here](https://cloud.google.com/config-connector/docs/how-to/managing-resources-with-resource-ids).

**Comment by mikesharpton-bestbuy** [comment]
Hello, thanks for your reply.  Can you tell me where/how I can look up the resourceID of a group?  I tried just the name, this failed.  

`d}`, but it contains an invalid `{groupd_id}`.
Details:
[
  {
    "@type": "type.googleapis.com/google.rpc.BadRequest",
    "fieldViolations": [
      {
        "description": "Error(2033): Group resource name has the correct format of `groups/{group_id}`, but it contains an invalid `{groupd_id}`.",
        "field": "name"
      }
    ]
  }
`

**Comment by mikesharpton-bestbuy** [comment]
We were able to figure out the gcloud command to get the group ID.

```
gcloud --project=projectid identity groups describe "groupname@domainname.com"
```

**Comment by mikesharpton-bestbuy** [comment]
I was able to acquire a group.  I am working on membership now, in which you need to lookup the resourceID once again.

```
gcloud identity groups memberships list --group-email=groupname@domainname.com --project=projectid
```

**Comment by toumorokoshi** [comment]
Thanks for replying back with the command! That's very helpful.

Yes, it seems that identity membership primarily works off of server-generated ids. It would be better if we could use some semantic name so the acquire flow can be easier, but those decisions are up to the service team and their API design. 

We could do some work on the Config Connector side to write some bespoke mapping logic, but that does come at the risk of being incompatible with new API behavior (e.g. if the unique ID we depend on like group email is no longer unique).

Is it fair to close this issue since a solution was found? If there's a desire for better acquire behavior, I'd suggest raising a cloud support ticket against cloudidentity: that tends to get better traction than internal escalation.

**Comment by mikesharpton-bestbuy** [comment]
Yes, we have our answers.  This can be closed.  Thanks!

**Comment by mikesharpton-bestbuy** [comment]
Also, I was able to acquire a group membership as well

**Comment by shahdghorsi** [comment]
@mikesharpton-bestbuy How did you do that with the code provided by google? [here](https://cloud.google.com/identity/docs/how-to/query-memberships#search-transitive-membership-python) I do not understand what to exactly put from the output I get after describing the group

**Comment by shahdghorsi** [comment]
> @mikesharpton-bestbuy How did you do that with the code provided by google? [here](https://cloud.google.com/identity/docs/how-to/query-memberships#search-transitive-membership-python) I do not understand what to exactly put from the output I get after describing the group

For whoever reads this, the group id you need should look like name: groups/8673hkdnjaod98f

Refer [this](https://stackoverflow.com/questions/70113262/fetch-google-group-members)

**Comment by bchkhaidze** [comment]
I ran into the same issue when moving Config Connector resources to a new namespace. I kept getting an “already exists” error.

Here’s how I resolved it:

1. Annotate the existing resource with `"abandon"` so Config Connector won’t delete the underlying GCP resource when the Kubernetes resource is removed:
```sh
cnrm.cloud.google.com/deletion-policy: "abandon"
```

2. Delete the resource from Kubernetes.

3. Recreate the resource with the following annotation:
```sh
cnrm.cloud.google.com/state-into-spec: "absent"
```

At this point, the resource may still fail because the group already exists.

4. Retrieve the group ID:
```sh
gcloud identity groups describe your-group-name@your-org.com
```

Example output:
```sh
name: groups/123abcxyz
```

5. Patch the resource with the `resourceID` using the value from the `name` field:
```sh
kubectl patch cloudidentitygroup crd_object_name -n your_namespace \
  --type=merge \
  -p '{"spec":{"resourceID":"groups/123abcxyz"}}'
```

After this, the resource should become **Ready**.

---

Make sure to replace any placeholders (group name, org, IDs) with your actual values before running these commands.
Also check the effects of the `state-into-spec` annotation [here](https://docs.cloud.google.com/config-connector/docs/concepts/managing-fields-externally)
