### ISSUE TITLE
consistent versions across CRD's and controller

### ISSUE THREAD

**Issue by nrobert13** [GoogleCloudPlatform/k8s-config-connector#61]
Hey guys,

would be nice to have a consistent versioning on the controller. Currently there are the versions of the CRD's in this repo, and some tags on the controller images, but no correlation...

**Comment by AlexBulankou** [comment]
@nrobert13 thanks for the suggestion! Let me clarify your use case. 
All the samples in this repo have been validated with the latest version of Config Connector that you can download from https://us-central1-cnrm-eap.cloudfunctions.net/download/latest/infra/install-bundle.tar.gz. You are correct that with every version there's a different tag on the controller image, but this tag is not the only thing that is changing from release to release, CRDs as well as all the objects in cnrm-system namespace are updated.

I can see two use cases for your question:
* Making sure that you have the latest Config Connector version so you can use all the samples in the repo
* Confirmation that a particular sample will still work on your version of Config Connector without upgrading to latest

Are these the scenarios or you had something else in mind?
Would a mapping table from controller image to release version help?

**Comment by nrobert13** [comment]
@AlexBulankou , so my usecase is now, that I run an older version of the controller, and the only solution I can see to check what resources I can use with the controller is to check the timestamp on the image tag and the closest realease version in this repo, and this is only an assumption, not sure if this should work. Basically your second use case.
A mapping table would definitely help, but an even better option would be to just add a second tag on the images with the release version from this repo the controller was validated with.

**Comment by toumorokoshi** [comment]
I'm going to close this issue since it's a bit old, but please re-open if you want to pick up the discussion.

Currently there continues to be no relationship between the CRD version and the config connector version. One reason for this is that the CRD schema itself doesn't change very frequently, and we would have to provide facilities in config connector to convert multiple CRD versions to a single storage schema (since Kubernetes only allows one storage schema, regardless of the representation). 

You can also query the config connector version, and correlate that with the CRDs in the repo (this is guaranteed to correlate):

`kubectl get ns cnrm-system -o jsonpath='{.metadata.annotations.cnrm\.cloud\.google\.com/version}'`

Check CRDs for appropriate tag: https://github.com/GoogleCloudPlatform/k8s-config-connector/tree/master/crds
