### ISSUE TITLE
Add region property for CloudBuildTrigger Resource

### ISSUE THREAD

**Issue by travisrandolph-bestbuy** [GoogleCloudPlatform/k8s-config-connector#672]
### Checklist

- [X] I did not find a related open enhancement request.
- [X] I understand that enhancement requests filed in the GitHub repository are by default low priority.
- [X] If this request is time-sensitive, I have submitted a corresponding issue with [GCP support](https://cloud.google.com/support-hub).

### Describe the feature or resource

The Cloud Build trigger API now supports region. We'd like to have this option for our KCC resources.

### Importance

This isn't a blocker, but currently our triggers and history pages don't match up. This is due to the fact that we are using custom worker pools that are in another region. If KCC supports the region property for CloudBuildTriggers we can change the region to match.

**Comment by travisrandolph-bestbuy** [comment]
I can't find the field either, but you can update the region via the console. I've added a screenshot showing the field.

<img width="558" alt="trigger" src="https://user-images.githubusercontent.com/75803296/175998142-495f73a1-31c5-4b74-b7fc-72062170d50f.png">

**Comment by caieo** [comment]
@travisrandolph-bestbuy, thank you for the request! Since your request is to support a new feature in one of our Terraform-based resources,
can you [file an enhancement request with Terraform](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) (if there isn't one yet)?

Note that timelines for Terraform resource requests can be pretty unpredictable. We recommend making the contribution yourself if possible (which we would also highly appreciate!).
Otherwise, we'll keep you posted on updates.

If you have other concerns or would like to escalate this request, please feel free to reach out to [GCP support](https://cloud.google.com/support-hub).

**Comment by travisrandolph-bestbuy** [comment]
@caieo it looks like [this issue](https://github.com/hashicorp/terraform-provider-google/issues/11624) was created to add support for location. It looks like the pull request with the change was just merged.

**Comment by mbzomowski** [comment]
@travisrandolph-bestbuy after they create a release with that change we'll upgrade our TF provider, and do a Config Connector release the week after that. Should be about 4 weeks FYI.

**Comment by mbzomowski** [comment]
`location` field is now included in `CloudBuildTrigger` as of Config Connector v 1.96.0.

**Comment by d47id** [comment]
I just upgraded from KCC 1.95.0 to 1.100.0 and no updates to CloudBuildTrigger resources are able to apply. I get `admission webhook "deny-immutable-field-updates.cnrm.cloud.google.com" denied the request: cannot make changes to immutable field(s): [location];` whether I include the location field in the manifest or not. Deleting and recreating the CloudBuildTrigger resources does not appear to work either. kubectl reports "DeletionFailed" in the resource status field.

Was this intended to be a breaking change? I think my only choice here is to delete the CloudBuildTrigger resources with abandon set, do the upgrade, then try and create them again and hope for the best.
