### ISSUE TITLE
Why doesn't ComputeRouterNAT expose TCP TIME_WAIT Timeout

### ISSUE THREAD

**Issue by sryabkov** [GoogleCloudPlatform/k8s-config-connector#692]
### Describe your question

Out of [five NAT timeouts](https://cloud.google.com/nat/docs/overview#specs-timeouts), Config Connector `ComputeRouterNAT` [seems to be exposing only four](https://cloud.google.com/config-connector/docs/reference/resource-docs/compute/computerouternat). Even though it is possible to change TCP TIME_WAIT Timeout [using the API](https://cloud.google.com/compute/docs/reference/rest/v1/routers) or [a gcloud command ](https://cloud.google.com/nat/docs/set-up-manage-network-address-translation#change_connection_timeouts_associated_with_nat), it is not possible to change it using Config Connector. Why is that?

The parameter is referred to as `tcpTimeWaitTimeoutSec` in the API and `--tcp-time-wait-timeout` in `gcloud compute routers nats update`.

**Comment by mbzomowski** [comment]
Hi @sryabkov, in order to support this new field, we rely on Terraform adding it to [google_compute_router_nat](https://registry.terraform.io/providers/wiardvanrij/ipv4google/latest/docs/resources/compute_router_nat). Please [file an enhancement request](https://github.com/hashicorp/terraform-provider-google/issues/new?assignees=&labels=enhancement&template=enhancement.md) in [terraform-provider-google repository](https://github.com/hashicorp/terraform-provider-google) if there isn't one already.

Unfortunately, the timeline for the completion of this request is unpredictable. We highly recommend you contribute to it yourself to accelerate the process, as Terraform is an open source project.

If you have other concerns, or would like to escalate this request, please reach out to us via [GCP support](https://cloud.google.com/support-hub).

**Comment by sryabkov** [comment]
@mbzomowski It seems to already been added, please see https://github.com/hashicorp/terraform-provider-google/pull/12174

**Comment by mbzomowski** [comment]
Ah you're right, in that case it'll get picked up the next time we upgrade our terraform provider, likely next week. Then it should be included in the next Config Connector release after that.

**Comment by mbzomowski** [comment]
@sryabkov correction - we won't be updating our Terraform provider this week. We should be updating it two weeks from now, so this change will be included in our release 3 weeks from now.
