### ISSUE TITLE
Is there  a known issue with deploying Cloud SQL through connector?

### ISSUE THREAD

**Issue by OchiengEd** [GoogleCloudPlatform/k8s-config-connector#7]
The musicians seemed to be taking a while to deploy and the delay is primarily during the creation of the Cloud SQL instance. 

The delay is okay, what am not clear about is whether the driver errors am seeing in the web container are as a result of the delay or if something else is going on.

**Note:**
I renamed my SQL instance to validate the issue; don't be perplexed by the instance name, `musicians-demo2`

```
$ kubectl logs musicians-686886cfd7-wz5sr -c web 
2019/06/18 20:55:57 DB_PASSWORD environment variable unspecified or ''
[mysql] 2019/06/18 20:55:57 packets.go:36: unexpected EOF
[mysql] 2019/06/18 20:55:57 packets.go:36: unexpected EOF
[mysql] 2019/06/18 20:55:57 packets.go:36: unexpected EOF
2019/06/18 20:55:57 Failed to create a database: driver: bad connection
$ gcloud sql instances list
NAME             DATABASE_VERSION  LOCATION       TIER              PRIMARY_ADDRESS  PRIVATE_ADDRESS  STATUS
musicians-demo2  MYSQL_5_7         us-central1-a  db-n1-standard-1  35.226.xxx.xxx   -                RUNNABLE
$ 
```

In addition, a look at the controller logs seems to confirm my initial suspicions. It does appear the controller is not able to sufficiently determine the state of a Cloud SQL instance.

```
E0619 15:48:30.874918       1 resource_processor_impl.go:434] Could not read response as json for google api sqladmin-v1beta4: reading the error from the request is not implemented
I0619 15:48:30.884195       1 dynamic_controller.go:101] [SQLInstance default/musicians-demo]: successfully finished reconcile
```

Lastly, deleting the sql instance is taking a while to complete. Would this be a good task to perform asynchronously to avoid holding the users prompt? Especially given the operator does not return any status from GCP regarding the task.

**Comment by kibbles-n-bytes** [comment]
Hey @OchiengEd ,

The driver errors on the `web` container are expected while the CloudSQL instance is being created. If you check the logs on the `cloudsql-proxy` container, you should see something like the following repeating:

```
2019/06/20 18:15:31 New connection for "[PROJECT]:us-central1:mymusiciansgithub-prod"
2019/06/20 18:15:31 Throttling refreshCfg([PROJECT]:us-central1:mymusiciansgithub-prod): it was only called 904.435094ms ago
2019/06/20 18:15:31 couldn't connect to "[PROJECT]:us-central1:mymusiciansgithub-prod": googleapi: Error 409: The instance or operation is not in an appropriate state to handle the request., invalidState
```

Eventually, once the instance is ready, the `web` container should then say:
```
2019/06/20 18:18:18 successfully connected to database: &{0xc42000e048 0 {0 0} [0xc420100180] map[] 0 1 0xc420062120 0xc420058120 false map[0xc420100180:map[0xc420100180:true]] map[] 0 0 0 <nil> 0x4b42c0}
2019/06/20 18:18:18 Server listening on port 8080
```

And the pod's status should become `Running`. We will likely add an init container to make the UX there smoother, as I definitely think the errors are misleading, even if things eventually become stable.

As for the deletion aspect, in the [CloudSQL section](https://github.com/GoogleCloudPlatform/k8s-config-connector#cloud-sql) at the bottom we have deletion instructions that use `kubectl delete --wait=false` in order to clean up asynchronously. It's unfortunately just a `kubectl` thing that by default it will not tell you anything about what's going on during resource deletion ☹️ . We do emit events and update our status whenever we start doing something, though, so if you check `kubectl describe sqlinstance` or `kubectl get events` you should see an event like `Deleting` and the status have a `Ready` condition with reason `Deleting` as well. Let me know if you aren't seeing those events or status updates, as that would mean there's a bug potentially.

**Comment by OchiengEd** [comment]
I will revisit the issue and get back to you.

**Comment by OchiengEd** [comment]
Using the `--wait=false` during delete of the `SQLInstance` seems to work.
