### ISSUE TITLE
How often is the Terraform Provider updated in the k8s-config-connector to regenerate/update CRDs?

### ISSUE THREAD

**Issue by stevefox** [GoogleCloudPlatform/k8s-config-connector#701]
### Describe your question

Hi, there's a feature that was added to the GCP Terraform provider about a month ago (matchesPrefix and matchesSuffix in the lifecycle rule found in resource_storage_bucket.go): https://github.com/hashicorp/terraform-provider-google/commit/f50ff8c842c0d7e080803c66326e8a858a98942cv

How frequently is the Terraform Provider updated in the KCC repo, from which CRDs are regenerated using TF2CRD? And once updated, how long does it take until it makes it into the managed version of Config Controller?

**Comment by mbzomowski** [comment]
_Generally_ we try to update the TF provider every other week, although due to various issues we skipped the last couple of updates. And usually once the TF provider is updated, we'll do a release the following week. We're finishing up a TF provider update right now, and we should have a release out by the end of the week (worst case next week) with those changes.

**Comment by stevefox** [comment]
Thanks for the update @mbzomowski!
