### ISSUE TITLE
Question rather than issue

### ISSUE THREAD

**Issue by rasalt** [GoogleCloudPlatform/k8s-config-connector#72]
Following the guide here: 
https://cloud.google.com/config-connector/docs/how-to/getting-started?authuser=0 to create a 
 kubectl --namespace rh20-260602 describe spannerinstance spannerinstance-sample
Name:         spannerinstance-sample
Namespace:    rh20-260602
Labels:       label-one=value-one
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"spanner.cnrm.cloud.google.com/v1alpha2","kind":"SpannerInstance","metadata":{"annotations":{},"labels":{"label-one":"value-...
API Version:  spanner.cnrm.cloud.google.com/v1alpha2
Kind:         SpannerInstance
Metadata:
  Creation Timestamp:  2019-12-16T16:27:41Z
  Generation:          1
  Resource Version:    3370780
  Self Link:           /apis/spanner.cnrm.cloud.google.com/v1alpha2/namespaces/rh20-260602/spannerinstances/spannerinstance-sample
  UID:                 fb82c2ea-2020-11ea-9244-42010a000005
Spec:
  Config:        regional-us-west1
  Display Name:  Spanner Instance Sample
  Num Nodes:     1
Events:          <none>

Is the expectation that this will create a Spanner Instance. Seeing the cloud console I don't see it.
Are there additional steps to follow to actually create a spanner instance ?
Thank you

**Comment by maqiuyujoyce** [comment]
Hi rasalt@, as we discussed offline, the missing "Status" field in your output meant that Config Connector was not running properly.
By running `kubectl get pods -n cnrm-system`, we found the failing pod. And by checking the logs of it, we identified that the root cause was your container couldn't run as root in your cluster.
Currently Config Connector requires the container to run as root. So once you fix the permission issue, you should be able to instantiate GCP resources via Config Connector.

Please let us if you have any additional questions.

**Comment by kibbles-n-bytes** [comment]
Followed up offline. Was an issue with KCC not being able to run as non-root in their environment. The latest release has KCC not running as root anymore, so the problem was solved.
