### ISSUE TITLE
Is config connector impacted by the Terraform relicensing?

### ISSUE THREAD

**Issue by coderanger** [GoogleCloudPlatform/k8s-config-connector#846]
### Describe your question

I'm sure you'll be discussing this internally a bunch but could we get some public guidance?

**Comment by EamonKeane** [comment]
They probably have a commercial relationship with Hashicorp so are unaffected for now. But afaik, GCP has deprecated Deployment Manager and has no provisioning solution fully independent of Terraform.

So I'd imagine they're deeply uncomfortable by this change and will be looking to remove this dependency in `k8s-config-connector`. Maybe they'll even support an open source fork.

**Comment by justinsb** [comment]
Thanks for the question.  It's a legal question so I don't want to go into too much detail, but all the versions of the libraries we're currently using have OSS-compatible licenses, and I believe that remains true today even with the latest versions of the libraries.

As with any OSS project, we have to make sure that all of our dependencies are OSS-compatible.  But that's actually more than just licensing - when code is linked into our binary, we want to be sure that they fix bugs and security vulnerabilities, are well maintained etc.  So if the license for any library were to change in future, or if any library became unmaintained, we would figure out a suitable way forwards - that's just "part of the deal" when using third party libraries.  Forking is always an option, but often I've found that stopping using a library can produce better outcomes all round.

As an example, this morning I noticed that our generated strongly-typed bindings pull in controller-runtime, and I don't think they should have to (because it seems likely to cause version conflicts for people that are using a different version of controller-runtime - maybe!).  I also noticed that we're using a collections library that was demonstrating the value of generics, but now that generics are well established it seems that library is not getting many updates.  So there are two small fixes in flight to tidy up those two dependencies (although obviously we're going to continue to use controller-runtime in our controllers themselves!).

I'm going to close, but if there is something I've overlooked please comment!
